# Database settings
spring.application.name=backend
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=vaultdb

# Max file upload size
spring.servlet.multipart.max-file-size=200000KB
spring.servlet.multipart.max-request-size=200000KB

# Default storage paths
THUMBNAILS_FOLDER_LOW_QUALITY=/home/educc/Documents/Vault-Project/other/vault_thumbnails/low_quality/
thumbnails.folder.low.quality=${THUMBNAILS_FOLDER_LOW_QUALITY}

THUMBNAILS_FOLDER_HIGH_QUALITY=/home/educc/Documents/Vault-Project/other/vault_thumbnails/high_quality/
thumbnails.folder.high.quality=${THUMBNAILS_FOLDER_HIGH_QUALITY}